name: CI Build & Push Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend    
          file: ./backend/Dockerfile
          push: true
          tags: habapa2k4/devops:backend-latest   
      # Build & push frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./learnking-frontend
          file: ./learnking-frontend/Dockerfile
          push: true
          tags: habapa2k4/devops:frontend-latest  